#!/bin/bash

HYPRCOOK_FILE_NAME="hyprcook"
HYPRCOOK_SOURCE_DIR="$HYPRCOOK_HOME/scripts"
HYPRCOOK_TARGET_DIR="$HOME/.local/bin"

SOURCE="$HYPRCOOK_SOURCE_DIR/$HYPRCOOK_FILE_NAME"
TARGET="$HYPRCOOK_TARGET_DIR/$HYPRCOOK_FILE_NAME"

mkdir -p "$HYPRCOOK_TARGET_DIR"

chmod +x "$SOURCE"

ln -sfn "$SOURCE" "$TARGET"
